### ISSUE TITLE
Class 'Cake\Mailer\Email' not found 

### ISSUE THREAD

**Issue by jimeshgajera** [motsmanish/cakephp-mailgun#1]
@motsmanish 

I have install cakephp-mailgun as per your installation step, but it is throw error as below

Error: Class 'Cake\Mailer\Email' not found

**Comment by motsmanish** [comment]
Did you add the below line at the top of your file?

use Cake\Mailer\Email;

Also, which CakePHP version have you installed?

**Comment by jimeshgajera** [comment]
@motsmanish 

Yes I have add this as below

use Cake\Mailer\Email;

**Comment by motsmanish** [comment]
which CakePHP version have you installed?

**Comment by jimeshgajera** [comment]
3.0.18

**Comment by motsmanish** [comment]
Must be related to this issue: https://github.com/cakephp/cakephp/issues/8583

Please upgrade your cake version to the latest one, if not possible, then at least to 3.1.8, (I have one of the apps running this plugin at 3.1.8)

**Comment by motsmanish** [comment]
Also please make sure, you have installed all required libraries via composer. ttyl.
